In [2]:
import numpy as np
import pandas as pd
pd.__version__

'0.21.1'

# `Series`

### simple, indices numericos

In [3]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [4]:
data.values

array([ 0.25,  0.5 ,  0.75,  1.  ])

In [5]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
data[2]

0.75

In [7]:
data.keys()

RangeIndex(start=0, stop=4, step=1)

### lista, indices personalizados

In [8]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [9]:
data[2]

0.75

In [10]:
data['c']

0.75

In [11]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

### diccionario, indices personalizados

In [12]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193
dtype: int64

In [13]:
population[2]

12882135

In [14]:
population[0:2]

California    38332521
Florida       19552860
dtype: int64

In [15]:
population['California']

38332521

In [16]:
population['California':'Illinois']

California    38332521
Florida       19552860
Illinois      12882135
dtype: int64

In [17]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

### `loc` e `iloc`

In [18]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

##### loc <references the explicit index:>

In [19]:
data.loc[1]

'a'

In [20]:
data.loc[1:3]

1    a
3    b
dtype: object

##### iloc <references the implicit Python-style index>

In [21]:
data.iloc[1]

'b'

In [22]:
data.iloc[1:3]

3    b
5    c
dtype: object

# inexistencia de valores

In [23]:
data = pd.Series([1, np.nan, 'hello', None])
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [24]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [25]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [26]:
data.fillna(0)

0        1
1        0
2    hello
3        0
dtype: object

##### dropna()

In [27]:
data.dropna()

0        1
2    hello
dtype: object

# `Dataframe`

# Creación

### forma 1

Creamos una serie

In [28]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
dtype: int64

Creamos un dataframe:

In [29]:
df = pd.DataFrame({'population': population,
                       'area': area})
df

area  population
California  423967    38332521
Florida     170312    19552860
Illinois    149995    12882135
New York    141297    19651127
Texas       695662    26448193

### forma 2

In [30]:
pd.DataFrame(population, columns=['population'])

population
California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193

### forma 3

In [59]:
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

foo       bar
a  0.372804  0.729756
b  0.534925  0.155666
c  0.521956  0.075576

In [87]:
df.head()

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [33]:
df.tail()

area  population
California  423967    38332521
Florida     170312    19552860
Illinois    149995    12882135
New York    141297    19651127
Texas       695662    26448193

In [34]:
df.describe()

area    population
count       5.000000  5.000000e+00
mean   316246.600000  2.337337e+07
std    242437.411951  9.640386e+06
min    141297.000000  1.288214e+07
25%    149995.000000  1.955286e+07
50%    170312.000000  1.965113e+07
75%    423967.000000  2.644819e+07
max    695662.000000  3.833252e+07

# columna como atributo

In [35]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
poblacion = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area': area, 'poblacion': poblacion})
data

area  poblacion
California  423967   38332521
Florida     170312   19552860
Illinois    149995   12882135
New York    141297   19651127
Texas       695662   26448193

In [36]:
data['area']

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [37]:
data.area

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

# operaciones

In [38]:
data['densidad'] = data['poblacion'] / data['area']
data

area  poblacion    densidad
California  423967   38332521   90.413926
Florida     170312   19552860  114.806121
Illinois    149995   12882135   85.883763
New York    141297   19651127  139.076746
Texas       695662   26448193   38.018740

In [39]:
data.values

array([[  4.23967000e+05,   3.83325210e+07,   9.04139261e+01],
       [  1.70312000e+05,   1.95528600e+07,   1.14806121e+02],
       [  1.49995000e+05,   1.28821350e+07,   8.58837628e+01],
       [  1.41297000e+05,   1.96511270e+07,   1.39076746e+02],
       [  6.95662000e+05,   2.64481930e+07,   3.80187404e+01]])

##### filas

In [40]:
data.values[0]  # fila 0

array([  4.23967000e+05,   3.83325210e+07,   9.04139261e+01])

In [41]:
data['Florida':'Illinois']

area  poblacion    densidad
Florida   170312   19552860  114.806121
Illinois  149995   12882135   85.883763

##### columnas

In [42]:
data['area']  # columna 'area'

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [43]:
data[1:3]

area  poblacion    densidad
Florida   170312   19552860  114.806121
Illinois  149995   12882135   85.883763

#### ambas

In [44]:
data[['poblacion', 'densidad']].loc[['Florida', 'California']]

poblacion    densidad
Florida      19552860  114.806121
California   38332521   90.413926

### filtrado

In [45]:
data.loc[data.densidad > 100, ['poblacion', 'densidad']]

poblacion    densidad
Florida    19552860  114.806121
New York   19651127  139.076746

### inexistencia de valores

In [46]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [47]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [48]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

### concatenacion

In [49]:
df1 = pd.DataFrame({'A': ['A1', 'A2'], 'B': ['B1', 'B2']}, index=[1, 2])
df2 = pd.DataFrame({'A': ['A3', 'A4'], 'B': ['B3', 'B4']}, index=[3, 4])

In [50]:
df1

A   B
1  A1  B1
2  A2  B2

In [51]:
df2

A   B
3  A3  B3
4  A4  B4

In [52]:
pd.concat([df1, df2])

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

#### mismo indice, ignorar

In [53]:
df1 = pd.DataFrame({'A': ['A1', 'A2'], 'B': ['B1', 'B2']}, index=[1, 2])
df2 = pd.DataFrame({'A': ['A3', 'A4'], 'B': ['B3', 'B4']}, index=[1, 2])

In [54]:
pd.concat([df1, df2], ignore_index=True)

A   B
0  A1  B1
1  A2  B2
2  A3  B3
3  A4  B4

### merge

In [55]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})

In [56]:
df1

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [57]:
df2

employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [58]:
df3 = pd.merge(df1, df2) # hint: how param!
df3

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014