In [3]:
import numpy as np
np.__version__

'1.13.3'

# `dtype`

A numpy array is homogeneous, and contains elements described by a dtype object.

* `np.int32`
* `np.int64`
* `np.float32`

Listado completo de tipos de elementos aquí: <br>
**https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html#array-types-and-conversions-between-types**

In [4]:
np.random.seed(0)  # seed for reproducibility

# Creación de arrays

### Arrays desde 0

In [5]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [6]:
np.array([3.14, 4, 2, 3]) # elemento de mayor info

array([ 3.14,  4.  ,  2.  ,  3.  ])

In [7]:
np.array([1, 2, 3, 4], dtype='float32')

array([ 1.,  2.,  3.,  4.], dtype=float32)

In [8]:
np.array([range(i, i + 3) for i in [2, 4, 6]]) # 2-dim

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Arrays desde 0 usando funciones

In [9]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.ones((2, 3), dtype=float)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [11]:
np.full((2, 3), 3.14)

array([[ 3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14]])

In [12]:
start, stop, step = 0, 20, 2
np.arange(start, stop, step)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
start, end, n_numbers = 0, 1, 5
np.linspace(start, end, n_numbers)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [14]:
np.random.random((3, 4))

array([[ 0.5488135 ,  0.71518937,  0.60276338,  0.54488318],
       [ 0.4236548 ,  0.64589411,  0.43758721,  0.891773  ],
       [ 0.96366276,  0.38344152,  0.79172504,  0.52889492]])

In [15]:
np.random.randint(0, 10, (3, 3))

array([[8, 1, 5],
       [9, 8, 9],
       [4, 3, 0]])

# Lo básico

### atributos

In [16]:
x1 = np.random.randint(10, size=6)          # 1-dim
x2 = np.random.randint(10, size=(3, 4))     # 2-dim
x3 = np.random.randint(10, size=(3, 4, 5))  # 3-dim

In [63]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [62]:
print("dtype:", x3.dtype)

dtype: int64


### Acceso simple

In [19]:
x1

array([3, 5, 0, 2, 3, 8])

In [60]:
print(x1[0])
print(x1[-1])

3
8


In [21]:
x2

array([[1, 3, 3, 3],
       [7, 0, 1, 9],
       [9, 0, 4, 7]])

In [59]:
print(x2[0, 0])
print(x2[2, -1])

12
7


In [23]:
x2[0, 0] = 12
x2

array([[12,  3,  3,  3],
       [ 7,  0,  1,  9],
       [ 9,  0,  4,  7]])

### Acceso múltiple

#### 1-dim

In [24]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
x[:5]

array([0, 1, 2, 3, 4])

In [26]:
x[1::2]

array([1, 3, 5, 7, 9])

In [27]:
x[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 2-dim

In [28]:
x2

array([[12,  3,  3,  3],
       [ 7,  0,  1,  9],
       [ 9,  0,  4,  7]])

In [29]:
x2[:2, :3]

array([[12,  3,  3],
       [ 7,  0,  1]])

In [30]:
x2[::-1, ::-1]

array([[ 7,  4,  0,  9],
       [ 9,  1,  0,  7],
       [ 3,  3,  3, 12]])

### copias

In [31]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy

array([[12,  3],
       [ 7,  0]])

In [32]:
x2_sub_copy[0, 0] = 42
x2_sub_copy

array([[42,  3],
       [ 7,  0]])

In [33]:
x2

array([[12,  3,  3,  3],
       [ 7,  0,  1,  9],
       [ 9,  0,  4,  7]])

### Re-dimensionamiento

In [57]:
x = np.array([1, 2, 3])
print(x.shape)
x

(3,)


array([1, 2, 3])

In [58]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

### Concatenacion

In [36]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [37]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

### Particionamiento

In [38]:
x = np.arange(8)
np.split(x, [3, 5, 6, 10])

[array([0, 1, 2]),
 array([3, 4]),
 array([5]),
 array([6, 7]),
 array([], dtype=int64)]

# UFuncs

For many types of operations, NumPy provides a convenient interface into just this kind of statically typed, compiled routine. This is known as a vectorized operation. 

Vectorized operations in NumPy are implemented via ufuncs,

### performance

In [39]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output


big_array = np.random.randint(1, 100, size=1000000)

In [40]:
%timeit compute_reciprocals(big_array)

2.34 s ± 80.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [41]:
%timeit (1.0 / big_array)

4.99 ms ± 789 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### uso

In [42]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [43]:
2 ** x

array([ 1,  2,  4,  8, 16])

In [44]:
(2 * x) + 5

array([ 5,  7,  9, 11, 13])

# Comparación

In [45]:
x

array([0, 1, 2, 3, 4])

In [46]:
x < 2

array([ True,  True, False, False, False], dtype=bool)

In [47]:
(2 * x) == (x ** 2)

array([ True, False,  True, False, False], dtype=bool)

In [48]:
A = np.array([1, 0, 1, 0, 1, 0], dtype=bool)
B = np.array([1, 1, 1, 0, 1, 1], dtype=bool)
A | B

array([ True,  True,  True, False,  True,  True], dtype=bool)

In [49]:
x = np.arange(10)
(x > 4) & (x < 8)

array([False, False, False, False, False,  True,  True,  True, False, False], dtype=bool)

In [50]:
x[x > 2] # mask

array([3, 4, 5, 6, 7, 8, 9])

# Agregación

In [51]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
x.min(), x.max()

(0, 9)

In [53]:
np.any(x < 2)

True

In [54]:
np.all(x < 2)

False

# Ordenamiento

In [55]:
x = np.array([2, 1, 4, 3, 5])

In [56]:
np.sort(x)

array([1, 2, 3, 4, 5])